### ISSUE TITLE
I can't compile this on the cdh5.10

### ISSUE THREAD

**Issue by Bosoon** [cloudera/impala-udf-samples#14]
Hello All,

I tried to compile this source code on the cdh5.10 ( nightly510 )
But I got this error during running make
[root@nightly510-unsecure-1 impala-udf-samples]# make
[ 16%] Building CXX object CMakeFiles/udasample.dir/uda-sample.cc.o
In file included from /root/impala-udf-samples/uda-sample.h:19,
                 from /root/impala-udf-samples/uda-sample.cc:15:
/usr/include/impala_udf/udf.h:23:29: error: boost/cstdint.hpp: No such file or directory
In file included from /root/impala-udf-samples/uda-sample.h:19,
                 from /root/impala-udf-samples/uda-sample.cc:15:
/usr/include/impala_udf/udf.h:86: error: ‘int64_t’ does not name a type
/usr/include/impala_udf/udf.h:87: error: ‘int64_t’ does not name a type
/usr/include/impala_udf/udf.h:147: error: expected ‘;’ before ‘*’ token
/usr/include/impala_udf/udf.h:163: error: expected ‘;’ before ‘*’ token
/usr/include/impala_udf/udf.h:166: error: ‘uint8_t’ has not been declared
/usr/include/impala_udf/udf.h:166: error: expected ‘;’ before ‘noexcept’
/usr/include/impala_udf/udf.h:172: error: ‘int64_t’ has not been declared
/usr/include/impala_udf/udf.h:173: error: ‘int64_t’ has not been declared
/usr/include/impala_udf/udf.h: In member function ‘T* impala_udf::FunctionContext::Allocate()’:
/usr/include/impala_udf/udf.h:152: error: no matching function for call to ‘impala_udf::FunctionContext::Allocate(long unsigned int&)’
/usr/include/impala_udf/udf.h: At global scope:
/usr/include/impala_udf/udf.h:416: error: ‘int8_t’ does not name a type
/usr/include/impala_udf/udf.h:418: error: expected ‘)’ before ‘val’
/usr/include/impala_udf/udf.h: In member function ‘bool impala_udf::TinyIntVal::operator==(const impala_udf::TinyIntVal&) const’:
/usr/include/impala_udf/udf.h:429: error: ‘val’ was not declared in this scope
/usr/include/impala_udf/udf.h:429: error: ‘const struct impala_udf::TinyIntVal’ has no member named ‘val’
/usr/include/impala_udf/udf.h: At global scope:
/usr/include/impala_udf/udf.h:435: error: ‘int16_t’ does not name a type
/usr/include/impala_udf/udf.h:437: error: expected ‘)’ before ‘val’
/usr/include/impala_udf/udf.h: In member function ‘bool impala_udf::SmallIntVal::operator==(const impala_udf::SmallIntVal&) const’:
/usr/include/impala_udf/udf.h:448: error: ‘val’ was not declared in this scope
/usr/include/impala_udf/udf.h:448: error: ‘const struct impala_udf::SmallIntVal’ has no member named ‘val’
/usr/include/impala_udf/udf.h: At global scope:
/usr/include/impala_udf/udf.h:454: error: ‘int32_t’ does not name a type
/usr/include/impala_udf/udf.h:456: error: expected ‘)’ before ‘val’
/usr/include/impala_udf/udf.h: In member function ‘bool impala_udf::IntVal::operator==(const impala_udf::IntVal&) const’:
/usr/include/impala_udf/udf.h:467: error: ‘val’ was not declared in this scope
/usr/include/impala_udf/udf.h:467: error: ‘const struct impala_udf::IntVal’ has no member named ‘val’
/usr/include/impala_udf/udf.h: At global scope:
/usr/include/impala_udf/udf.h:473: error: ‘int64_t’ does not name a type
/usr/include/impala_udf/udf.h:475: error: expected ‘)’ before ‘val’
/usr/include/impala_udf/udf.h: In member function ‘bool impala_udf::BigIntVal::operator==(const impala_udf::BigIntVal&) const’:
/usr/include/impala_udf/udf.h:486: error: ‘val’ was not declared in this scope
/usr/include/impala_udf/udf.h:486: error: ‘const struct impala_udf::BigIntVal’ has no member named ‘val’
/usr/include/impala_udf/udf.h: At global scope:
/usr/include/impala_udf/udf.h:530: error: ‘int32_t’ does not name a type
/usr/include/impala_udf/udf.h:532: error: ‘int64_t’ does not name a type
/usr/include/impala_udf/udf.h:534: error: expected ‘)’ before ‘date’
/usr/include/impala_udf/udf.h: In member function ‘bool impala_udf::TimestampVal::operator==(const impala_udf::TimestampVal&) const’:
/usr/include/impala_udf/udf.h:547: error: ‘date’ was not declared in this scope
/usr/include/impala_udf/udf.h:547: error: ‘const struct impala_udf::TimestampVal’ has no member named ‘date’
/usr/include/impala_udf/udf.h:547: error: ‘time_of_day’ was not declared in this scope
/usr/include/impala_udf/udf.h:547: error: ‘const struct impala_udf::TimestampVal’ has no member named ‘time_of_day’
/usr/include/impala_udf/udf.h: At global scope:
/usr/include/impala_udf/udf.h:561: error: expected ‘;’ before ‘*’ token
/usr/include/impala_udf/udf.h:565: error: expected ‘)’ before ‘*’ token
/usr/include/impala_udf/udf.h:581: error: expected ‘;’ before ‘noexcept’
/usr/include/impala_udf/udf.h:590: error: expected ‘,’ or ‘...’ before ‘*’ token
/usr/include/impala_udf/udf.h:590: error: expected ‘;’ before ‘noexcept’
/usr/include/impala_udf/udf.h: In constructor ‘impala_udf::StringVal::StringVal(const char*)’:
/usr/include/impala_udf/udf.h:572: error: class ‘impala_udf::StringVal’ does not have any field named ‘ptr’
/usr/include/impala_udf/udf.h:572: error: ‘uint8_t’ was not declared in this scope
/usr/include/impala_udf/udf.h:572: error: expected primary-expression before ‘)’ token
/usr/include/impala_udf/udf.h: In static member function ‘static impala_udf::StringVal impala_udf::StringVal::null()’:
/usr/include/impala_udf/udf.h:593: error: no matching function for call to ‘impala_udf::StringVal::StringVal()’
/usr/include/impala_udf/udf.h:572: note: candidates are: impala_udf::StringVal::StringVal(const char*)
/usr/include/impala_udf/udf.h:554: note:                 impala_udf::StringVal::StringVal(const impala_udf::StringVal&)
/usr/include/impala_udf/udf.h: In member function ‘bool impala_udf::StringVal::operator==(const impala_udf::StringVal&) const’:
/usr/include/impala_udf/udf.h:602: error: ‘ptr’ was not declared in this scope
/usr/include/impala_udf/udf.h:602: error: ‘const struct impala_udf::StringVal’ has no member named ‘ptr’
/usr/include/impala_udf/udf.h:602: error: ‘const struct impala_udf::StringVal’ has no member named ‘ptr’
/usr/include/impala_udf/udf.h: At global scope:
/usr/include/impala_udf/udf.h:622: error: ‘int32_t’ does not name a type
/usr/include/impala_udf/udf.h:623: error: ‘int64_t’ does not name a type
/usr/include/impala_udf/udf.h:628: error: expected ‘)’ before ‘v’
/usr/include/impala_udf/udf.h:629: error: expected ‘)’ before ‘v’
/usr/include/impala_udf/udf.h:652: error: expected initializer before ‘*’ token
/root/impala-udf-samples/uda-sample.cc: In function ‘impala_udf::StringVal ToStringVal(impala_udf::FunctionContext*, const T&)’:
/root/impala-udf-samples/uda-sample.cc:28: error: ‘struct impala_udf::StringVal’ has no member named ‘ptr’
/root/impala-udf-samples/uda-sample.cc: In function ‘void CountInit(impala_udf::FunctionContext*, impala_udf::BigIntVal*)’:
/root/impala-udf-samples/uda-sample.cc:43: error: ‘struct impala_udf::BigIntVal’ has no member named ‘val’
/root/impala-udf-samples/uda-sample.cc: In function ‘void CountUpdate(impala_udf::FunctionContext*, const impala_udf::IntVal&, impala_udf::BigIntVal*)’:
/root/impala-udf-samples/uda-sample.cc:48: error: ‘struct impala_udf::BigIntVal’ has no member named ‘val’
/root/impala-udf-samples/uda-sample.cc: In function ‘void CountMerge(impala_udf::FunctionContext*, const impala_udf::BigIntVal&, impala_udf::BigIntVal*)’:
/root/impala-udf-samples/uda-sample.cc:52: error: ‘struct impala_udf::BigIntVal’ has no member named ‘val’
/root/impala-udf-samples/uda-sample.cc:52: error: ‘const struct impala_udf::BigIntVal’ has no member named ‘val’
/root/impala-udf-samples/uda-sample.cc: At global scope:
/root/impala-udf-samples/uda-sample.cc:64: error: ‘int64_t’ does not name a type
/root/impala-udf-samples/uda-sample.cc: In function ‘void AvgInit(impala_udf::FunctionContext*, impala_udf::StringVal*)’:
/root/impala-udf-samples/uda-sample.cc:71: error: ‘struct impala_udf::StringVal’ has no member named ‘ptr’
/root/impala-udf-samples/uda-sample.cc:71: error: no matching function for call to ‘impala_udf::FunctionContext::Allocate(int&)’
/root/impala-udf-samples/uda-sample.cc:72: error: ‘struct impala_udf::StringVal’ has no member named ‘ptr’
/root/impala-udf-samples/uda-sample.cc: In function ‘void AvgUpdate(impala_udf::FunctionContext*, const impala_udf::DoubleVal&, impala_udf::StringVal*)’:
/root/impala-udf-samples/uda-sample.cc:79: error: ‘struct impala_udf::StringVal’ has no member named ‘ptr’
/root/impala-udf-samples/uda-sample.cc:81: error: ‘struct AvgStruct’ has no member named ‘count’
/root/impala-udf-samples/uda-sample.cc: In function ‘void AvgMerge(impala_udf::FunctionContext*, const impala_udf::StringVal&, impala_udf::StringVal*)’:
/root/impala-udf-samples/uda-sample.cc:86: error: ‘const struct impala_udf::StringVal’ has no member named ‘ptr’
/root/impala-udf-samples/uda-sample.cc:87: error: ‘struct impala_udf::StringVal’ has no member named ‘ptr’
/root/impala-udf-samples/uda-sample.cc:89: error: ‘struct AvgStruct’ has no member named ‘count’
/root/impala-udf-samples/uda-sample.cc:89: error: ‘const struct AvgStruct’ has no member named ‘count’
/root/impala-udf-samples/uda-sample.cc: In function ‘const impala_udf::StringVal AvgSerialize(impala_udf::FunctionContext*, const impala_udf::StringVal&)’:
/root/impala-udf-samples/uda-sample.cc:99: error: no matching function for call to ‘impala_udf::StringVal::StringVal(impala_udf::FunctionContext*&, const int&)’
/usr/include/impala_udf/udf.h:572: note: candidates are: impala_udf::StringVal::StringVal(const char*)
/usr/include/impala_udf/udf.h:554: note:                 impala_udf::StringVal::StringVal(const impala_udf::StringVal&)
/root/impala-udf-samples/uda-sample.cc:100: error: ‘struct impala_udf::StringVal’ has no member named ‘ptr’
/root/impala-udf-samples/uda-sample.cc:100: error: ‘const struct impala_udf::StringVal’ has no member named ‘ptr’
/root/impala-udf-samples/uda-sample.cc:101: error: ‘const struct impala_udf::StringVal’ has no member named ‘ptr’
/root/impala-udf-samples/uda-sample.cc: In function ‘impala_udf::StringVal AvgFinalize(impala_udf::FunctionContext*, const impala_udf::StringVal&)’:
/root/impala-udf-samples/uda-sample.cc:108: error: ‘const struct impala_udf::StringVal’ has no member named ‘ptr’
/root/impala-udf-samples/uda-sample.cc:109: error: no matching function for call to ‘impala_udf::StringVal::StringVal()’
/usr/include/impala_udf/udf.h:572: note: candidates are: impala_udf::StringVal::StringVal(const char*)
/usr/include/impala_udf/udf.h:554: note:                 impala_udf::StringVal::StringVal(const impala_udf::StringVal&)
/root/impala-udf-samples/uda-sample.cc:110: error: ‘struct AvgStruct’ has no member named ‘count’
/root/impala-udf-samples/uda-sample.cc:114: error: ‘struct AvgStruct’ has no member named ‘count’
/root/impala-udf-samples/uda-sample.cc:116: error: ‘const struct impala_udf::StringVal’ has no member named ‘ptr’
/root/impala-udf-samples/uda-sample.cc: At global scope:
/root/impala-udf-samples/uda-sample.cc:125: error: ‘uint8_t’ was not declared in this scope
/root/impala-udf-samples/uda-sample.cc:125: error: expected primary-expression before ‘)’ token
/root/impala-udf-samples/uda-sample.cc: In function ‘void StringConcatUpdate(impala_udf::FunctionContext*, const impala_udf::StringVal&, const impala_udf::StringVal&, impala_udf::StringVal*)’:
/root/impala-udf-samples/uda-sample.cc:136: error: ‘uint8_t’ was not declared in this scope
/root/impala-udf-samples/uda-sample.cc:136: error: no matching function for call to ‘impala_udf::FunctionContext::Allocate(const int&)’
/root/impala-udf-samples/uda-sample.cc:137: error: ‘const struct impala_udf::StringVal’ has no member named ‘ptr’
/root/impala-udf-samples/uda-sample.cc:138: error: no matching function for call to ‘impala_udf::StringVal::StringVal(<unresolved overloaded function type>, const int&)’
/usr/include/impala_udf/udf.h:572: note: candidates are: impala_udf::StringVal::StringVal(const char*)
/usr/include/impala_udf/udf.h:554: note:                 impala_udf::StringVal::StringVal(const impala_udf::StringVal&)
/root/impala-udf-samples/uda-sample.cc:148: error: ‘struct impala_udf::StringVal’ has no member named ‘ptr’
/root/impala-udf-samples/uda-sample.cc:148: error: ‘class impala_udf::FunctionContext’ has no member named ‘Reallocate’
/root/impala-udf-samples/uda-sample.cc:148: error: ‘struct impala_udf::StringVal’ has no member named ‘ptr’
/root/impala-udf-samples/uda-sample.cc:149: error: ‘struct impala_udf::StringVal’ has no member named ‘ptr’
/root/impala-udf-samples/uda-sample.cc:149: error: ‘const struct impala_udf::StringVal’ has no member named ‘ptr’
/root/impala-udf-samples/uda-sample.cc:151: error: ‘struct impala_udf::StringVal’ has no member named ‘ptr’
/root/impala-udf-samples/uda-sample.cc:151: error: ‘const struct impala_udf::StringVal’ has no member named ‘ptr’
/root/impala-udf-samples/uda-sample.cc: In function ‘const impala_udf::StringVal StringConcatSerialize(impala_udf::FunctionContext*, const impala_udf::StringVal&)’:
/root/impala-udf-samples/uda-sample.cc:167: error: no matching function for call to ‘impala_udf::StringVal::StringVal(impala_udf::FunctionContext*&, const int&)’
/usr/include/impala_udf/udf.h:572: note: candidates are: impala_udf::StringVal::StringVal(const char*)
/usr/include/impala_udf/udf.h:554: note:                 impala_udf::StringVal::StringVal(const impala_udf::StringVal&)
/root/impala-udf-samples/uda-sample.cc:168: error: ‘struct impala_udf::StringVal’ has no member named ‘ptr’
/root/impala-udf-samples/uda-sample.cc:168: error: ‘const struct impala_udf::StringVal’ has no member named ‘ptr’
/root/impala-udf-samples/uda-sample.cc:169: error: ‘const struct impala_udf::StringVal’ has no member named ‘ptr’
/root/impala-udf-samples/uda-sample.cc: In function ‘impala_udf::StringVal StringConcatFinalize(impala_udf::FunctionContext*, const impala_udf::StringVal&)’:
/root/impala-udf-samples/uda-sample.cc:176: error: no matching function for call to ‘impala_udf::StringVal::StringVal(impala_udf::FunctionContext*&, const int&)’
/usr/include/impala_udf/udf.h:572: note: candidates are: impala_udf::StringVal::StringVal(const char*)
/usr/include/impala_udf/udf.h:554: note:                 impala_udf::StringVal::StringVal(const impala_udf::StringVal&)
/root/impala-udf-samples/uda-sample.cc:177: error: ‘struct impala_udf::StringVal’ has no member named ‘ptr’
/root/impala-udf-samples/uda-sample.cc:177: error: ‘const struct impala_udf::StringVal’ has no member named ‘ptr’
/root/impala-udf-samples/uda-sample.cc:178: error: ‘const struct impala_udf::StringVal’ has no member named ‘ptr’
/root/impala-udf-samples/uda-sample.cc: In function ‘impala_udf::StringVal ToStringVal(impala_udf::FunctionContext*, const T&) [with T = double]’:
/root/impala-udf-samples/uda-sample.cc:35:   instantiated from here
/root/impala-udf-samples/uda-sample.cc:27: error: no matching function for call to ‘impala_udf::StringVal::StringVal(impala_udf::FunctionContext*&, size_t)’
/usr/include/impala_udf/udf.h:572: note: candidates are: impala_udf::StringVal::StringVal(const char*)
/usr/include/impala_udf/udf.h:554: note:                 impala_udf::StringVal::StringVal(const impala_udf::StringVal&)
make[2]: *** [CMakeFiles/udasample.dir/uda-sample.cc.o] Error 1
make[1]: *** [CMakeFiles/udasample.dir/all] Error 2
make: *** [all] Error 2

**Comment by timarmstrong** [comment]
There was a bug with the 5.9.x and 5.10.x impala-udf-dev packages. If you downgrade that package to 5.8.x or upgrade to 5.11.x (once that is released) it should work fine. The impala-udf-dev package doesn't need to exactly match the impala version.
