### ISSUE TITLE
Unable to locate udf_samples.tar.gz file

### ISSUE THREAD

**Issue by harsheel87** [cloudera/impala-udf-samples#19]
The README.md file mentions "Install the impala udf development package: http://archive.cloudera.com/cdh5/". What is the name of this development package? I am using Debian 8 (Jessie) with CDH 5.10 and would like to try the udf samples. I have downloaded few things from that location but I am unable to find the "udf_samples.tar.gz" file in any of my downloaded files; I am probably missing something simple.

**Comment by timarmstrong** [comment]
The debian Jessie packages are under here: http://archive.cloudera.com/cdh5/debian/jessie/amd64/cdh/pool/contrib/i/impala/

You can add it as an apt repo and install the usual way with apt-get following the instructions here: https://www.cloudera.com/documentation/enterprise/latest/topics/cdh_ig_cdh5_install.html#topic_4_4_1__p_44

**Comment by harsheel87** [comment]
Thank you for your response, Tim. I was able to locate the required files.
