### ISSUE TITLE
UDF Impala libstdc++.so.6

### ISSUE THREAD

**Issue by MacJei** [cloudera/impala-udf-samples#29]
Hello

I'm create udf, and have next problem. Can you help me?

ERROR: AnalysisException: Could not load binary: /user/impala/udfs/libudfcrypto.so Unable to load /var/lib/impala/udfs/libudfcrypto.669611.10.so dlerror: /opt/cloudera/parcels/CDH-5.15.1-1.cdh5.15.1.p0.4/lib/impala/lib/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /var/lib/impala/udfs/libudfcrypto.669611.10.so)

**Comment by timarmstrong** [comment]
It looks like you compiled against a newer libstdc++.so than the one that Impala uses (your UDF will link against Impala's version at runtime, and it appears to be too old).

What OS is this on? 

What compiler version? I.e. output of gcc --version?

What commit of impala-udf-samples are you using?

**Comment by MacJei** [comment]
Tim, thank you for help me.

UDF created on Ubuntu, and run on RHEL 7.

gcc = 7.4.0 where created, and 4.8 where run.

i just downloaded it from here https://github.com/cloudera/impala-udf-samples
Impala Shell v2.12.0-cdh5.15.1

**Comment by VarnitKhandelwal** [comment]
I am still facing the same issue, I have tried compiling with the **gcc version - 7.5.0**
And our CDH version is 6.3.2
And Impala Version is 3.2.0

Please help us with it.

**Comment by MacJei** [comment]
@VarnitKhandelwal I collected it in Docker and it worked for me. It is necessary that gcc coincides with what is on the prod and where you collect. https://github.com/MacJei/UDF-Impala
